<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AdminController extends Controller
{
//    fun ction index() {
////        echo "halo selamat datang";
////        echo "<h1> Halo ". Auth::user()->name ."</h1>";
////        echo "<a href='/logout'>LogOut>></a>";
//        public function __call($method, $parameters)
//        {
//            parent::__call($method, $parameters); // TODO: Change the autogenerated stub
//        }
//}

    function admin(){
//        echo "halo admin";
//        echo "<h1> Halo ". Auth::user()->name ."</h1>";
//        echo "<a href='/logout'>LogOut>></a>";

        return view('homeadmin.homeadmin');

    }
    function team(){
//        echo "halo selamat datang";
//        echo "<h1> Halo ". Auth::user()->name ."</h1>";
//        echo "<a href='/logout'>LogOut>></a>";
        return view('homepage.index');
    }
}
